version: "3.6"

services:
  php:
    build: ./docker/php/
    # container_name: myproject_php
    restart: unless-stopped
    volumes:
      - .:/var/www
    links:
      - mysql

  nginx:
    image: nginx:1.17.0-alpine
    # container_name: myproject_nginx
    restart: unless-stopped
    ports:
      - 80:80
    links:
      - php
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - .:/var/www

  mysql:
    image: mysql:8.0.16
    # container_name: myproject_mysql
    restart: unless-stopped
    ports:
      - 3307:3306
    volumes:
      - .db-data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
      - ./docker/mysql/conf:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  cache:
    image: redis:3
    ports:
      - "6380:6379"
    restart: always
    volumes:
      - .cache-data:/data
    command: "redis-server --requirepass ${REDIS_PASSWORD}"

volumes:
  db-data:
  cache-data:
